name: branch-protection

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-software:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./software
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606
        with:
          target: thumbv8m.main-none-eabihf
          components: clippy
      - run: cargo clippy -- -D warnings

  lint-hardware:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad@sha256:6bd21a8e12eaa6fab7ca72818c6af4e441be53b5b82f2d1d611208827d9a7cc7
      # https://docs.github.com/en/actions/reference/workflows-and-actions/dockerfile-support#user
      options: --user root
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # https://docs.github.com/en/actions/reference/workflows-and-actions/dockerfile-support#user
      - run: |
          su - kicad -c "cd $GITHUB_WORKSPACE/hardware/MCP9601-Sensor && kicad-cli pcb drc --exit-code-violations --severity-error --schematic-parity -o /tmp/report MCP9601-Sensor.kicad_pcb"
      - run: |
          su - kicad -c "cd $GITHUB_WORKSPACE/hardware/STM32H533-Breakout && kicad-cli pcb drc --exit-code-violations --severity-error --schematic-parity -o /tmp/report STM32H533-Breakout.kicad_pcb"
      - run: |
          su - kicad -c "cd $GITHUB_WORKSPACE/hardware/TPS631000-Buck-Boost-Converter && kicad-cli pcb drc --exit-code-violations --severity-error --schematic-parity -o /tmp/report TPS631000-Buck-Boost-Converter.kicad_pcb"

  required-checks:
    runs-on: ubuntu-latest
    needs:
      - lint-software
      - lint-hardware
    steps:
      - run: echo true
